name: ignite_cli
description: Ignite your projects with flame; a CLI scaffolding tool to create and setup your Flame projects
version: 0.1.0
homepage: https://flame-engine.org/ignite

environment:
  sdk: '>=2.9.3 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
